services:
  db:
    image: mysql:8.0
    container_name: db_imobiliaria
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  api:
    build: .
    container_name: api_imobiliaria
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - API_PORT=3333
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3333:3333"
    volumes:
    - .:/usr/app 
    - /usr/app/node_modules
volumes:
  mysql_data:
  